name: PlayerDataRecordConfig
type: class
category:
memory_category: Instances
summary: ''
description: ''
code_samples: []
inherits:
  - Instance
tags:
  - NotCreatable
  - NotReplicated
deprecation_message: ''
properties:
  - name: PlayerDataRecordConfig.RecordName
    summary: ''
    description: ''
    code_samples: []
    type: string
    tags:
      - ReadOnly
      - NotReplicated
    deprecation_message: ''
    security:
      read: None
      write: None
    thread_safety: ReadSafe
    category: Data
    serialization:
      can_load: false
      can_save: true
    capabilities: []
    writeCapabilities: []
methods:
  - name: PlayerDataRecordConfig:GetDefaultValue
    summary: ''
    description: ''
    code_samples: []
    parameters:
      - name: key
        type: string
        default:
        summary: ''
    returns:
      - type: Variant
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
  - name: PlayerDataRecordConfig:SetDefaultValue
    summary: ''
    description: ''
    code_samples: []
    parameters:
      - name: key
        type: string
        default:
        summary: ''
      - name: value
        type: Variant
        default:
        summary: ''
    returns:
      - type: void
        summary: ''
    tags: []
    deprecation_message: ''
    security: None
    thread_safety: Unsafe
    capabilities: []
    writeCapabilities: []
events: []
callbacks: []
